//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Bandl.VaultLedger.Web.Printing {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsFindMedium : DataSet {
        
        private HeaderLogoDataTable tableHeaderLogo;
        
        private MediumDataTable tableMedium;
        
        public dsFindMedium() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsFindMedium(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["HeaderLogo"] != null)) {
                    this.Tables.Add(new HeaderLogoDataTable(ds.Tables["HeaderLogo"]));
                }
                if ((ds.Tables["Medium"] != null)) {
                    this.Tables.Add(new MediumDataTable(ds.Tables["Medium"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public HeaderLogoDataTable HeaderLogo {
            get {
                return this.tableHeaderLogo;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public MediumDataTable Medium {
            get {
                return this.tableMedium;
            }
        }
        
        public override DataSet Clone() {
            dsFindMedium cln = ((dsFindMedium)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["HeaderLogo"] != null)) {
                this.Tables.Add(new HeaderLogoDataTable(ds.Tables["HeaderLogo"]));
            }
            if ((ds.Tables["Medium"] != null)) {
                this.Tables.Add(new MediumDataTable(ds.Tables["Medium"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableHeaderLogo = ((HeaderLogoDataTable)(this.Tables["HeaderLogo"]));
            if ((this.tableHeaderLogo != null)) {
                this.tableHeaderLogo.InitVars();
            }
            this.tableMedium = ((MediumDataTable)(this.Tables["Medium"]));
            if ((this.tableMedium != null)) {
                this.tableMedium.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsFindMedium";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsFindMedium.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableHeaderLogo = new HeaderLogoDataTable();
            this.Tables.Add(this.tableHeaderLogo);
            this.tableMedium = new MediumDataTable();
            this.Tables.Add(this.tableMedium);
        }
        
        private bool ShouldSerializeHeaderLogo() {
            return false;
        }
        
        private bool ShouldSerializeMedium() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void HeaderLogoRowChangeEventHandler(object sender, HeaderLogoRowChangeEvent e);
        
        public delegate void MediumRowChangeEventHandler(object sender, MediumRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HeaderLogoDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnCompanyLogo;
            
            private DataColumn columnProductLogo;
            
            private DataColumn columnReportTitle;
            
            internal HeaderLogoDataTable() : 
                    base("HeaderLogo") {
                this.InitClass();
            }
            
            internal HeaderLogoDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn CompanyLogoColumn {
                get {
                    return this.columnCompanyLogo;
                }
            }
            
            internal DataColumn ProductLogoColumn {
                get {
                    return this.columnProductLogo;
                }
            }
            
            internal DataColumn ReportTitleColumn {
                get {
                    return this.columnReportTitle;
                }
            }
            
            public HeaderLogoRow this[int index] {
                get {
                    return ((HeaderLogoRow)(this.Rows[index]));
                }
            }
            
            public event HeaderLogoRowChangeEventHandler HeaderLogoRowChanged;
            
            public event HeaderLogoRowChangeEventHandler HeaderLogoRowChanging;
            
            public event HeaderLogoRowChangeEventHandler HeaderLogoRowDeleted;
            
            public event HeaderLogoRowChangeEventHandler HeaderLogoRowDeleting;
            
            public void AddHeaderLogoRow(HeaderLogoRow row) {
                this.Rows.Add(row);
            }
            
            public HeaderLogoRow AddHeaderLogoRow(System.Byte[] CompanyLogo, System.Byte[] ProductLogo, string ReportTitle) {
                HeaderLogoRow rowHeaderLogoRow = ((HeaderLogoRow)(this.NewRow()));
                rowHeaderLogoRow.ItemArray = new object[] {
                        CompanyLogo,
                        ProductLogo,
                        ReportTitle};
                this.Rows.Add(rowHeaderLogoRow);
                return rowHeaderLogoRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                HeaderLogoDataTable cln = ((HeaderLogoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new HeaderLogoDataTable();
            }
            
            internal void InitVars() {
                this.columnCompanyLogo = this.Columns["CompanyLogo"];
                this.columnProductLogo = this.Columns["ProductLogo"];
                this.columnReportTitle = this.Columns["ReportTitle"];
            }
            
            private void InitClass() {
                this.columnCompanyLogo = new DataColumn("CompanyLogo", typeof(System.Byte[]), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCompanyLogo);
                this.columnProductLogo = new DataColumn("ProductLogo", typeof(System.Byte[]), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProductLogo);
                this.columnReportTitle = new DataColumn("ReportTitle", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnReportTitle);
            }
            
            public HeaderLogoRow NewHeaderLogoRow() {
                return ((HeaderLogoRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new HeaderLogoRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(HeaderLogoRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.HeaderLogoRowChanged != null)) {
                    this.HeaderLogoRowChanged(this, new HeaderLogoRowChangeEvent(((HeaderLogoRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.HeaderLogoRowChanging != null)) {
                    this.HeaderLogoRowChanging(this, new HeaderLogoRowChangeEvent(((HeaderLogoRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.HeaderLogoRowDeleted != null)) {
                    this.HeaderLogoRowDeleted(this, new HeaderLogoRowChangeEvent(((HeaderLogoRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.HeaderLogoRowDeleting != null)) {
                    this.HeaderLogoRowDeleting(this, new HeaderLogoRowChangeEvent(((HeaderLogoRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveHeaderLogoRow(HeaderLogoRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HeaderLogoRow : DataRow {
            
            private HeaderLogoDataTable tableHeaderLogo;
            
            internal HeaderLogoRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableHeaderLogo = ((HeaderLogoDataTable)(this.Table));
            }
            
            public System.Byte[] CompanyLogo {
                get {
                    try {
                        return ((System.Byte[])(this[this.tableHeaderLogo.CompanyLogoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHeaderLogo.CompanyLogoColumn] = value;
                }
            }
            
            public System.Byte[] ProductLogo {
                get {
                    try {
                        return ((System.Byte[])(this[this.tableHeaderLogo.ProductLogoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHeaderLogo.ProductLogoColumn] = value;
                }
            }
            
            public string ReportTitle {
                get {
                    try {
                        return ((string)(this[this.tableHeaderLogo.ReportTitleColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHeaderLogo.ReportTitleColumn] = value;
                }
            }
            
            public bool IsCompanyLogoNull() {
                return this.IsNull(this.tableHeaderLogo.CompanyLogoColumn);
            }
            
            public void SetCompanyLogoNull() {
                this[this.tableHeaderLogo.CompanyLogoColumn] = System.Convert.DBNull;
            }
            
            public bool IsProductLogoNull() {
                return this.IsNull(this.tableHeaderLogo.ProductLogoColumn);
            }
            
            public void SetProductLogoNull() {
                this[this.tableHeaderLogo.ProductLogoColumn] = System.Convert.DBNull;
            }
            
            public bool IsReportTitleNull() {
                return this.IsNull(this.tableHeaderLogo.ReportTitleColumn);
            }
            
            public void SetReportTitleNull() {
                this[this.tableHeaderLogo.ReportTitleColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HeaderLogoRowChangeEvent : EventArgs {
            
            private HeaderLogoRow eventRow;
            
            private DataRowAction eventAction;
            
            public HeaderLogoRowChangeEvent(HeaderLogoRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public HeaderLogoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MediumDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnSerialNo;
            
            private DataColumn columnLocation;
            
            private DataColumn columnMediumType;
            
            private DataColumn columnAccount;
            
            private DataColumn columnMissing;
            
            private DataColumn columnReturnDate;
            
            private DataColumn columnCaseName;
            
            private DataColumn columnLastMoveDate;
            
            private DataColumn columnNotes;
            
            internal MediumDataTable() : 
                    base("Medium") {
                this.InitClass();
            }
            
            internal MediumDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn SerialNoColumn {
                get {
                    return this.columnSerialNo;
                }
            }
            
            internal DataColumn LocationColumn {
                get {
                    return this.columnLocation;
                }
            }
            
            internal DataColumn MediumTypeColumn {
                get {
                    return this.columnMediumType;
                }
            }
            
            internal DataColumn AccountColumn {
                get {
                    return this.columnAccount;
                }
            }
            
            internal DataColumn MissingColumn {
                get {
                    return this.columnMissing;
                }
            }
            
            internal DataColumn ReturnDateColumn {
                get {
                    return this.columnReturnDate;
                }
            }
            
            internal DataColumn CaseNameColumn {
                get {
                    return this.columnCaseName;
                }
            }
            
            internal DataColumn LastMoveDateColumn {
                get {
                    return this.columnLastMoveDate;
                }
            }
            
            internal DataColumn NotesColumn {
                get {
                    return this.columnNotes;
                }
            }
            
            public MediumRow this[int index] {
                get {
                    return ((MediumRow)(this.Rows[index]));
                }
            }
            
            public event MediumRowChangeEventHandler MediumRowChanged;
            
            public event MediumRowChangeEventHandler MediumRowChanging;
            
            public event MediumRowChangeEventHandler MediumRowDeleted;
            
            public event MediumRowChangeEventHandler MediumRowDeleting;
            
            public void AddMediumRow(MediumRow row) {
                this.Rows.Add(row);
            }
            
            public MediumRow AddMediumRow(string SerialNo, string Location, string MediumType, string Account, string Missing, string ReturnDate, string CaseName, string LastMoveDate, string Notes) {
                MediumRow rowMediumRow = ((MediumRow)(this.NewRow()));
                rowMediumRow.ItemArray = new object[] {
                        SerialNo,
                        Location,
                        MediumType,
                        Account,
                        Missing,
                        ReturnDate,
                        CaseName,
                        LastMoveDate,
                        Notes};
                this.Rows.Add(rowMediumRow);
                return rowMediumRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                MediumDataTable cln = ((MediumDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new MediumDataTable();
            }
            
            internal void InitVars() {
                this.columnSerialNo = this.Columns["SerialNo"];
                this.columnLocation = this.Columns["Location"];
                this.columnMediumType = this.Columns["MediumType"];
                this.columnAccount = this.Columns["Account"];
                this.columnMissing = this.Columns["Missing"];
                this.columnReturnDate = this.Columns["ReturnDate"];
                this.columnCaseName = this.Columns["CaseName"];
                this.columnLastMoveDate = this.Columns["LastMoveDate"];
                this.columnNotes = this.Columns["Notes"];
            }
            
            private void InitClass() {
                this.columnSerialNo = new DataColumn("SerialNo", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSerialNo);
                this.columnLocation = new DataColumn("Location", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLocation);
                this.columnMediumType = new DataColumn("MediumType", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMediumType);
                this.columnAccount = new DataColumn("Account", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAccount);
                this.columnMissing = new DataColumn("Missing", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMissing);
                this.columnReturnDate = new DataColumn("ReturnDate", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnReturnDate);
                this.columnCaseName = new DataColumn("CaseName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCaseName);
                this.columnLastMoveDate = new DataColumn("LastMoveDate", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLastMoveDate);
                this.columnNotes = new DataColumn("Notes", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNotes);
            }
            
            public MediumRow NewMediumRow() {
                return ((MediumRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new MediumRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(MediumRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.MediumRowChanged != null)) {
                    this.MediumRowChanged(this, new MediumRowChangeEvent(((MediumRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.MediumRowChanging != null)) {
                    this.MediumRowChanging(this, new MediumRowChangeEvent(((MediumRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.MediumRowDeleted != null)) {
                    this.MediumRowDeleted(this, new MediumRowChangeEvent(((MediumRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.MediumRowDeleting != null)) {
                    this.MediumRowDeleting(this, new MediumRowChangeEvent(((MediumRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveMediumRow(MediumRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MediumRow : DataRow {
            
            private MediumDataTable tableMedium;
            
            internal MediumRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableMedium = ((MediumDataTable)(this.Table));
            }
            
            public string SerialNo {
                get {
                    try {
                        return ((string)(this[this.tableMedium.SerialNoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.SerialNoColumn] = value;
                }
            }
            
            public string Location {
                get {
                    try {
                        return ((string)(this[this.tableMedium.LocationColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.LocationColumn] = value;
                }
            }
            
            public string MediumType {
                get {
                    try {
                        return ((string)(this[this.tableMedium.MediumTypeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.MediumTypeColumn] = value;
                }
            }
            
            public string Account {
                get {
                    try {
                        return ((string)(this[this.tableMedium.AccountColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.AccountColumn] = value;
                }
            }
            
            public string Missing {
                get {
                    try {
                        return ((string)(this[this.tableMedium.MissingColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.MissingColumn] = value;
                }
            }
            
            public string ReturnDate {
                get {
                    try {
                        return ((string)(this[this.tableMedium.ReturnDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.ReturnDateColumn] = value;
                }
            }
            
            public string CaseName {
                get {
                    try {
                        return ((string)(this[this.tableMedium.CaseNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.CaseNameColumn] = value;
                }
            }
            
            public string LastMoveDate {
                get {
                    try {
                        return ((string)(this[this.tableMedium.LastMoveDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.LastMoveDateColumn] = value;
                }
            }
            
            public string Notes {
                get {
                    try {
                        return ((string)(this[this.tableMedium.NotesColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMedium.NotesColumn] = value;
                }
            }
            
            public bool IsSerialNoNull() {
                return this.IsNull(this.tableMedium.SerialNoColumn);
            }
            
            public void SetSerialNoNull() {
                this[this.tableMedium.SerialNoColumn] = System.Convert.DBNull;
            }
            
            public bool IsLocationNull() {
                return this.IsNull(this.tableMedium.LocationColumn);
            }
            
            public void SetLocationNull() {
                this[this.tableMedium.LocationColumn] = System.Convert.DBNull;
            }
            
            public bool IsMediumTypeNull() {
                return this.IsNull(this.tableMedium.MediumTypeColumn);
            }
            
            public void SetMediumTypeNull() {
                this[this.tableMedium.MediumTypeColumn] = System.Convert.DBNull;
            }
            
            public bool IsAccountNull() {
                return this.IsNull(this.tableMedium.AccountColumn);
            }
            
            public void SetAccountNull() {
                this[this.tableMedium.AccountColumn] = System.Convert.DBNull;
            }
            
            public bool IsMissingNull() {
                return this.IsNull(this.tableMedium.MissingColumn);
            }
            
            public void SetMissingNull() {
                this[this.tableMedium.MissingColumn] = System.Convert.DBNull;
            }
            
            public bool IsReturnDateNull() {
                return this.IsNull(this.tableMedium.ReturnDateColumn);
            }
            
            public void SetReturnDateNull() {
                this[this.tableMedium.ReturnDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsCaseNameNull() {
                return this.IsNull(this.tableMedium.CaseNameColumn);
            }
            
            public void SetCaseNameNull() {
                this[this.tableMedium.CaseNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsLastMoveDateNull() {
                return this.IsNull(this.tableMedium.LastMoveDateColumn);
            }
            
            public void SetLastMoveDateNull() {
                this[this.tableMedium.LastMoveDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsNotesNull() {
                return this.IsNull(this.tableMedium.NotesColumn);
            }
            
            public void SetNotesNull() {
                this[this.tableMedium.NotesColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MediumRowChangeEvent : EventArgs {
            
            private MediumRow eventRow;
            
            private DataRowAction eventAction;
            
            public MediumRowChangeEvent(MediumRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public MediumRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
