<div style="BORDER-RIGHT:#27274f 1px solid;BACKGROUND:url(./img/topBar.gif) repeat-x; WIDTH:779px; POSITION:relative; HEIGHT:59px">
    <div style="Z-INDEX:2;LEFT:30px;POSITION:absolute;TOP:16px">
        <IMG alt="Recall Logo" src="img/recallLogo.gif">
    </div>
    <div style="Z-INDEX:2;LEFT:131px;POSITION:absolute;TOP:22px">
        <IMG height="15" alt="ReQuest Logo" src="img/reQuestLogo.gif" width="153" border="0">
    </div>
    <div style="FLOAT:right; MARGIN:24px 6px 0px 0px" align="right">
    <div style="font:12px tahoma,arial,sans-serif;font-weight:bold;color:#27274F">
    Service Administration
    </div>
    </div>
</div>
<div style="BORDER-TOP:#000 1px solid;BORDER-RIGHT:#27274f 1px solid;BORDER-BOTTOM:1px solid #000;background:#00529B;POSITION:relative;WIDTH:779px;HEIGHT:21px">
</div>
